
[scheduler]
    [scheduler.batch]
        interval = 60

[plugins]
    [plugins.psutil]
        [plugins.psutil.cpu]
            enabled = true
            per_cpu_threshold = 0.2
            total_cpu_threshold = 0.25

[eventhandler]
    [eventhandler.inactivetimeout]
        die_on_inactive = false

        [eventhandler.inactivetimeout.command]
            command = "echo"
            parameters = ["Computer", "is idle"]